remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme

description: ""

show_sidebar: true # show a sidebar instead of the usual header

# Menu

navigation: # accepts {file, title, url, icon, sidebaricon}
  - { url: "cisco/python-fundamentals/README.md", icon: python }
  - { url: "azure/az-900/README.md", icon: cloud }
  - { url: "escola-da-nuvem/aws-fundamentals/README.md", icon: aws }
  - { url: "google_cloud/associate_cloud_engineer/README.md", icon: google }
  - { url: "udemy/angular15/README.md", icon: angular }
